### ISSUE TITLE
バザール->会場->バザール->会場と遷移すると、会場に遷移しなくなりますね

### ISSUE THREAD

**Issue by sys1yagi** [mhidaka/EventApp#18]
<blockquote class="twitter-tweet" lang="ja"><p><a href="https://twitter.com/sys1yagi">@sys1yagi</a> Activityが再生成された後の動きが何か変ですね。バザール-&gt;会場-&gt;バザール-&gt;会場と遷移すると、会場に遷移しなくなりますね</p>&mdash; fkm (@fkm) <a href="https://twitter.com/fkm/statuses/446608069850443776">2014, 3月 20</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by fkmhrk** [comment]
これ、FragmentManagerの管理下にいるFragmentにPlacementFragmentが複数いるのが原因っぽい

**Comment by sys1yagi** [comment]
あ、なるほど。つまり各画面を実装してxxFragmentが増えていけば解決する感じですね。
